/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as DroogsRouteImport } from './routes/droogs'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DroogsIndexRouteImport } from './routes/droogs.index'
import { Route as OgTypeRouteImport } from './routes/og/$type'
import { Route as DroogsUsernameRouteImport } from './routes/droogs.$username'
import { Route as ApiDebugRouteImport } from './routes/api/debug'
import { Route as ApiRpcSplatRouteImport } from './routes/api.rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const DroogsRoute = DroogsRouteImport.update({
  id: '/droogs',
  path: '/droogs',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DroogsIndexRoute = DroogsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DroogsRoute,
} as any)
const OgTypeRoute = OgTypeRouteImport.update({
  id: '/og/$type',
  path: '/og/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const DroogsUsernameRoute = DroogsUsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => DroogsRoute,
} as any)
const ApiDebugRoute = ApiDebugRouteImport.update({
  id: '/api/debug',
  path: '/api/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRoute
  '/droogs': typeof DroogsRouteWithChildren
  '/report': typeof ReportRoute
  '/api/debug': typeof ApiDebugRoute
  '/droogs/$username': typeof DroogsUsernameRoute
  '/og/$type': typeof OgTypeRoute
  '/droogs/': typeof DroogsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRoute
  '/report': typeof ReportRoute
  '/api/debug': typeof ApiDebugRoute
  '/droogs/$username': typeof DroogsUsernameRoute
  '/og/$type': typeof OgTypeRoute
  '/droogs': typeof DroogsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/debug': typeof DebugRoute
  '/droogs': typeof DroogsRouteWithChildren
  '/report': typeof ReportRoute
  '/api/debug': typeof ApiDebugRoute
  '/droogs/$username': typeof DroogsUsernameRoute
  '/og/$type': typeof OgTypeRoute
  '/droogs/': typeof DroogsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/debug'
    | '/droogs'
    | '/report'
    | '/api/debug'
    | '/droogs/$username'
    | '/og/$type'
    | '/droogs/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/debug'
    | '/report'
    | '/api/debug'
    | '/droogs/$username'
    | '/og/$type'
    | '/droogs'
    | '/api/auth/$'
    | '/api/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/debug'
    | '/droogs'
    | '/report'
    | '/api/debug'
    | '/droogs/$username'
    | '/og/$type'
    | '/droogs/'
    | '/api/auth/$'
    | '/api/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DebugRoute: typeof DebugRoute
  DroogsRoute: typeof DroogsRouteWithChildren
  ReportRoute: typeof ReportRoute
  ApiDebugRoute: typeof ApiDebugRoute
  OgTypeRoute: typeof OgTypeRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/droogs': {
      id: '/droogs'
      path: '/droogs'
      fullPath: '/droogs'
      preLoaderRoute: typeof DroogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/droogs/': {
      id: '/droogs/'
      path: '/'
      fullPath: '/droogs/'
      preLoaderRoute: typeof DroogsIndexRouteImport
      parentRoute: typeof DroogsRoute
    }
    '/og/$type': {
      id: '/og/$type'
      path: '/og/$type'
      fullPath: '/og/$type'
      preLoaderRoute: typeof OgTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/droogs/$username': {
      id: '/droogs/$username'
      path: '/$username'
      fullPath: '/droogs/$username'
      preLoaderRoute: typeof DroogsUsernameRouteImport
      parentRoute: typeof DroogsRoute
    }
    '/api/debug': {
      id: '/api/debug'
      path: '/api/debug'
      fullPath: '/api/debug'
      preLoaderRoute: typeof ApiDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DroogsRouteChildren {
  DroogsUsernameRoute: typeof DroogsUsernameRoute
  DroogsIndexRoute: typeof DroogsIndexRoute
}

const DroogsRouteChildren: DroogsRouteChildren = {
  DroogsUsernameRoute: DroogsUsernameRoute,
  DroogsIndexRoute: DroogsIndexRoute,
}

const DroogsRouteWithChildren =
  DroogsRoute._addFileChildren(DroogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DebugRoute: DebugRoute,
  DroogsRoute: DroogsRouteWithChildren,
  ReportRoute: ReportRoute,
  ApiDebugRoute: ApiDebugRoute,
  OgTypeRoute: OgTypeRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
